_target_: the_well.benchmark.models.sinenet.SineNet
n_input_scalar_components: 2
n_input_vector_components: 1
n_output_scalar_components: 2
n_output_vector_components: 1
time_history: 4
time_future: 1
hidden_channels: 42
padding_mode: "circular"
activation: "gelu"
num_layers: 4
num_waves: 2
num_blocks: 1
norm: True
mult: 1.2
